### ISSUE TITLE
[BOOTSTRAP - docker] | Feature - Setting up docker

### ISSUE THREAD

**Issue by hugomonteiro-datai-engineering** [divinoPV/scoutix#1]
**Tasks:**

- [x] make two environments, either dev and prod
- global : 
  - [x] mariadb:10.8
  - [x] phpmyadmin
  - [x] mailhog
- dev : 
  - [x] nginx:stable-alpine : 
    - default.conf
  - [x] node:17.7.1-alpine
  - [x] php:8.1-fpm, with : 
    - php.ini
    - pool.conf
    - symfony.conf 
- [x] .dockerignore

**Constraints:**

- use docker compose v2
- separate services into files for different environments
