### ISSUE TITLE
[AUTHENTICATION - login] | Feature - Make login form

### ISSUE THREAD

**Issue by hugomonteiro-datai-engineering** [divinoPV/scoutix#10]
**Tasks:**
  - [x] Make login form
  - [x] Authentication system
  - [x] Repair make start
  - [x] Correct Birthdable => birthGender return type
  - [x] Correct Genderum random functions
  - [x] Bootstrap refresh token
  - [x] Refactor atomic design folder
  - [x] add api ressource to user properties

**Constraints:**
  - [x] email for login

**Behaviors:**
  - AU01 | OPT
  - AU02

**Dependencies:**
  - #22
