### ISSUE TITLE
[AUTHENTICATION - connected homepage] | Feature - Make connected homepage

### ISSUE THREAD

**Issue by hugomonteiro-datai-engineering** [divinoPV/scoutix#12]
**Tasks:**
  - [x] Make connected homepage

**Constraints:**
  - [ ] Availabled scopes display
  - [x] Diary and event creation page display if current user scope allowed

**Behaviors:**
  - [x] PA02
  - [ ] PA03-A | OPT
  - [ ] AG05
  - [ ] GA06
  - [x] ME02

**Dependencies:**
  - #10
