### ISSUE TITLE
[AUTHENTICATION - change scope] | Feature - Change scope

### ISSUE THREAD

**Issue by divinoPV** [divinoPV/scoutix#13]
**Tasks:**
  - [x] Can change the scope

**Constraints:**
  - [x] User is connected
  - [x] Among my scopes

**Behaviors:**
  - [ ] AU04 | OPT

**Dependencies:**
  - #12
