### ISSUE TITLE
[BACK OFFICE - role authorization] | Feature - Authorization per role

### ISSUE THREAD

**Issue by Spacelocust** [divinoPV/scoutix#14]
**Tasks:**
  - [x] Make function (user role) form 
  - [x] Make feature form
  - [x] Attribute functions to features 

**Constraints:**
  - [x] Need Admin role

**Behaviors:**
  - [ ] GA06
