### ISSUE TITLE
[BACK OFFICE - crud user] | Feature - Crud user

### ISSUE THREAD

**Issue by Spacelocust** [divinoPV/scoutix#18]
**Tasks:**
  - [x] Make user crud
  - [x] Setting up ApiPlatform
  - [x] Make page
  - [x] Create table
  - [x]  Config table 

**Constraints:**
  - [x] Need Admin role

**Behaviors:**
  - TR02 | OPT
