### ISSUE TITLE
[BOOTSTRAP - api] | Feature - Setting up api

### ISSUE THREAD

**Issue by hugomonteiro-datai-engineering** [divinoPV/scoutix#2]
**Tasks:**

- set up .env file : 
  - [x] global
  - [x] ci
- [x] .gherkin-lintrc
- [x] .php-cs-fixer.php
- [x] .sensiolabs.yml
- [x] phpunit.xml.dist
- generate tests folder : 
  - [x] Integration
  - [x] Unit
- [x] generate the symfony project
