### ISSUE TITLE
[AUTHENTICATION - disconnect homepage] | Feature - Make the disconnect homepage

### ISSUE THREAD

**Issue by hugomonteiro-datai-engineering** [divinoPV/scoutix#22]
**Tasks:**
  - [x] Make the disconnect homepage

**Constraints:**
  - [x] I must see login button in navbar
  - [x] Scoutix logo is present in the navigation bar
  - [x] Slider containing the latest news/events before the fold (= ligne de flotaison), for the moment display static data
  - [x] Grid of 12 items from the last articles, for the moment display static data
  - [x] Grid of 12 items from the last events, for the moment display static data

**Behaviors:**
  - [x] PA01
