### ISSUE TITLE
[BOOTSTRAP - entities] | Feature - Generate all entities, traits, contracts, enums, fixtures and puml

### ISSUE THREAD

**Issue by hugomonteiro-datai-engineering** [divinoPV/scoutix#23]
**Tasks:**
  - [x] Generate all entities
  - [x] Create puml
  - [x] Create contract for each entity
  - [x] Create contract for each trait
  - [x] Create all the enums needed
  - [x] Create fixtures for each entity
  - [x] Translations for each enum case
  - [x] Change default shell of docker containers

**Constraints:**
  - Entities:
    - [x] AuthorizationFunctionFeature (relation between Function/Feature)
    - [x] AuthorizationEventCategory (relation between Function/EventCategory), switch property to define if is default
    - [x] Feature
    - [x] Activity (= function)
    - [x] Event
    - [x] EventCategory (relation OtM Event)
    - [x] EventInvitation (relation MtO [EventCategory, Function, Scope, User])
    - [x] Locality
    - [x] News
    - [x] NewsCategory (relation OtM News)
    - [x] Role
    - [x] Scope (relation between Function/Locality)
    - [x] User
  - [x] Relation properties in entity
  - [x] Optimize entities by creating traits
  - [x] Genderalization and pluralization of enums cases trans
