### ISSUE TITLE
[DOCUMENTATION - github templates] | Feature - Generate all GitHub templates

### ISSUE THREAD

**Issue by hugomonteiro-datai-engineering** [divinoPV/scoutix#27]
**Tasks:**
  - Issues:
    - [ ] feature
    - [ ] bug
    - [ ] improvement (to talk about making a thing better that is not so good now)
    - [ ] enhancement (to talk about making a good thing even better)
    - [ ] generic
    - [ ] documentation
    - [ ] refactor
    - [ ] test
  - [ ] pull request template
