### ISSUE TITLE
[BOOTSTRAP - client] | Feature - Setting up client

### ISSUE THREAD

**Issue by hugomonteiro-datai-engineering** [divinoPV/scoutix#3]
**Tasks:**

- [x] .eslintrc
- [x] .sasslintrc
- [x] generate components folder following the Atomic design architecture
- [x] generate style folder following bemit
- [x] create react app typescript
- [x] set up typescript for react
