### ISSUE TITLE
[ARCHITECTURE - site] | Feature - add a disjunction between BO & FO

### ISSUE THREAD

**Issue by Spacelocust** [divinoPV/scoutix#42]
**Tasks:**

- [x] separate BO & FO with condition in index.tsx
- [x] add new routing
- [x] add a new store
