### ISSUE TITLE
[STATE - store] |  Feature - Persist store & Reload state user & Reset state user

### ISSUE THREAD

**Issue by Spacelocust** [divinoPV/scoutix#54]
**Tasks:**
  - [x] Create persist store HOC
  - [x]  Create reload state user function
  - [x]  Delete user state & localStorage data
